version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "signal-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5b5nte4kjsjn"
s3_prefix = "signal-api"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
