AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  signal-aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  CreateRoomFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: signal-app/
      Handler: app.createRoom
      Runtime: nodejs12.x
      Events:
        CreateRoom:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /room
            Method: post
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-2dbfd04f
        SubnetIds:
          - subnet-32955f59
          - subnet-48596704
          - subnet-97d782cb
          - subnet-d0fe79ab
  GetRoomFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: signal-app/
      Handler: app.getRoom
      Runtime: nodejs12.x
      Events:
        GetRoom:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /room/{roomId}
            Method: post
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - sg-2dbfd04f
        SubnetIds:
          - subnet-32955f59
          - subnet-48596704
          - subnet-97d782cb
          - subnet-d0fe79ab

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RoomApi:
    Description: "API Gateway endpoint URL for Prod stage for Managing Room function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/room/"
  CreateRoomFunction:
    Description: "Create Room Lambda Function ARN"
    Value: !GetAtt CreateRoomFunction.Arn
  CreateRoomFunctionIamRole:
    Description: "Implicit IAM Role created for Create Room function"
    Value: !GetAtt CreateRoomFunctionRole.Arn
  GetRoomFunction:
    Description: "Get Room Lambda Function ARN"
    Value: !GetAtt GetRoomFunction.Arn
  GetRoomFunctionIamRole:
    Description: "Implicit IAM Role created for Get Room function"
    Value: !GetAtt GetRoomFunctionRole.Arn
