name: CI
env:
  INPUT_REGION: ap-northeast-2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.INPUT_REGION }}


      - name: AWS SAM Build
        uses: TractorZoom/sam-cli-action@v.0.2.0
        with:
          sam_command: "build -t signal.sam.yaml"

      - name: AWS SAM Deploy
        uses: TractorZoom/sam-cli-action@v.0.2.0
        with:
          sam_command: "deploy  --no-confirm-changeset --no-progressbar"

